name: open-blinkist-api
services:
  - environment_slug: python
    github:
      branch: main
      deploy_on_push: true
    name: api
    routes:
      - path: /
    build_command: pip install -r requirements.txt
    run_command: python start_production.py
    source_dir: /
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: PORT
        value: "8080"
      - key: GROQ_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ALLOWED_ORIGINS
        value: "http://localhost:3000,http://127.0.0.1:3000,https://open-blinkist.vercel.app"
    http_port: 8080
